language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: lXWBm7pyt+rUmdOWeSsrs8Ty+d9e0XAVMWLpqGcZ6jLaHhYbN110CQ1u7qmqLCyG0Z7eYBo3PH7EL4vlYE2QNfKW7EiHGYfVzonIs2DDtCeM2ZuBNFT3Rqp1DWBuainnKRvjeVAlyOu+0pFDvk+RWnnf2XCL8eUi/jWWDChgekRz4TaROdOMDAmhHYlvkFXtpFJ3X1dRIFxOi9KSQfyccBX0txyNzvDlfu72UAWdfz2f6shei05DJ7bo+VeOFuXMh0CylGhblTGL5y1VDSgRagYDOJ88DzzM4e4kqyY51d2kqJNeTcwhd67XWk1xhsohYA01hC1ZYsYn6V9XEFVsUF54us+xILqlIcMGOPyZNx6CbEZv3lZn5nLPxG38AumiV+4xH3n/erlbx6hFo+HrtNg+5gktwp1fv+BErRZQ5wo+fZrd/TqKJo78+3f2GpmPJDPBjqUsxQEC2JrJs8bMtdizvgx3G2Yqa9r1O9vmX1YcUkKr+7vF6sXUU5JPhs0r+4Bv0MSJQgOE0HSAFaW6aOlNQ+9h1pQvt6JEEvil9kvf5BpYkqFe5oCWwMOd8lXv/6NDsSfBtPR65FKsQaOmdfaupP6CnAlncWRIU01Va4e935/Du62wttyEvpfUvlyPQgJqFbb3N+qmh2+61b1YbspABxaBjy1zbIYjNpsJ4UI=
  app: LPA2_PROJET
  on:
    repo: oacardoso/LPA2_PROJET
