language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: 6eLgql8cVHhHZA2w5cHdaYwb6WWZwM2rxjp7IIpLLHjiy34nfAw6/jthrCbB1nukY2vt3O6fRp6ASk3uLzWwQmh0NGWJ5hL51BIxVHhHQrnU/FZaHkO8aCQvWk+qY6bSEcPHwzSxR9dBvYWPirUvO0D8ZQpe/ooaIx97kUVenZJ/Y1JmLKH52+AyQStG0NaldwxGrw21XZ5TZF7EszIRLDRGjYWNE6/TRobo3mu5sGrtxrR3V5/bi86DBZSaXofwe7l9AsEDYdgk8DgM3Bse/HB1gcJ0g5odUi3eaEBS0H0yOPK/rHCD26nujPWZuzcWGyfmoJruqkfodr3HoalYGGXe8/lS0lcXqmiu82f97JblnFcU0WAh0wXQHyJj22mm6hcNri3l/0L8faQXP7G+l0W3b2jVgmgf9YjxelTPRoTOWgLOCIza5tRXZmh+ZzTfCMj5TwAMN2QiJVd1tXNh9qxFLs5X238nS4M0WTPJSUDV0cUhyP0/a47kukGQGQCRIHcdA9lj6vA35HmeizoGdn64bRn0P89qAIAvD6/csPfo7qV0P1RETKNCkkajJv9gSo/y69NWTcXdlArnxJwaxdLe2I2mExdhXnHtXsEHdUcyMtPNU0h36kjLZD4X7uRaHkgIFeTlLLrDB85n9sY0Zce49RfQIPCp3cL+sDVjwYE=
  app: stark-basin-13873
  on:
    repo: oacardoso/LPA2_PROJET
