language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: 4pis2z0R2nzpxbUwdDAae/53aTSRKgVejck56UEaL27sl+1G7rUpRQvLzPEWd05cAF6NlRf05T4LeHka01DNsYPzSHouldRGl9X+mPdAoRTRp70uwzVJUAewSmnCEvGumWg97g/1bPIss2uD+HM+pT1CIT9nF4W4jK2tWtNpWa5CxYS1dzD3B2VFwWIwYn2FonfJ/wwxd6D2GzCtZhbKvLnECFMc2v9SScuSbodssO6lbUGqwlojnrsGA0F8py+knITh9WGbICvQJThfIZ7jHzE+gerbQlq+3wFysN1S4+YRtTkbs+5J9OMnsERfnONkzWN1vNYSl5QxUjB4Ve9Onmzp4AjuotyUGFodYQN5dvUcehv3AfZwOE1XVrdCZrXx2a31pxwyFDBHz/LdXH7DCB7uREjZbbV0qw/MCzagXDesa3jmgaGXaRdcV+p4j2jSZoZfEiC5xsRDziWlysI8LjOoreIi0pS5+Xf74Z9VDNRNfeBWLGjvrBXtoNA/KIdR2+eekKfWmKas74NpqdtDBcUejFzIIz3wgn531yX6fUeZU7H32mMX6a9N2hRS4TXaqZu0+OFon8oeym/qI43nH3+C40T7rPlz42itCAV4WKdJvS6rNM3ps/LNKs9XSJCKxVKQ9mUGXhPECWLbdxBCRSCyNst8DtDN3xD5DClf7iM=
  app: shrouded-fortress-67001
  on:
    repo: oacardoso/LPA2_PROJET
sudo: required
dist: trusty
addons:
    code_climate:
        repo_token: 402982d8b8299bd628b7a26353bf785216aa5209cd9c4fa85c5f5bdcd8963e77
# regular test configuration
after_success:
  - bundle exec codeclimate-test-reporter

